from supabase import create_client, Client

SUPABASE_URL = "https://hwxyuvtfoyzycggbypmo.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3eHl1dnRmb3l6eWNnZ2J5cG1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5OTY5NTYsImV4cCI6MjA2ODU3Mjk1Nn0._pvwyaNrQbBTwp7440b-5bMRJs4jmkk_TtRCl6H5llA"

supabase = create_client(SUPABASE_URL , SUPABASE_KEY)